// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPygygKNiHzJNWS0FIRr6Lq2wcsALRRa4',
    appId: '1:113719455885:web:9f5c7b7bb272a1fc9772c4',
    messagingSenderId: '113719455885',
    projectId: 'esp32-heartrate',
    authDomain: 'esp32-heartrate.firebaseapp.com',
    databaseURL: 'https://esp32-heartrate-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-heartrate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyQRsJfHo7Q3utnFYG23cIbU6yfwjs40Q',
    appId: '1:113719455885:android:60632bee865f9f879772c4',
    messagingSenderId: '113719455885',
    projectId: 'esp32-heartrate',
    databaseURL: 'https://esp32-heartrate-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-heartrate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALUY6IlkAygO-69qc7BXUu6j-3aWVPrdc',
    appId: '1:113719455885:ios:9b0102aba4fd28499772c4',
    messagingSenderId: '113719455885',
    projectId: 'esp32-heartrate',
    databaseURL: 'https://esp32-heartrate-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-heartrate.appspot.com',
    iosBundleId: 'com.example.capapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALUY6IlkAygO-69qc7BXUu6j-3aWVPrdc',
    appId: '1:113719455885:ios:fee8a7c2cf25f9f29772c4',
    messagingSenderId: '113719455885',
    projectId: 'esp32-heartrate',
    databaseURL: 'https://esp32-heartrate-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-heartrate.appspot.com',
    iosBundleId: 'com.example.capapp.RunnerTests',
  );
}
